spring:
  application:
    name: mall-coupon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_coupon?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.mall.coupon.model
server:
  port: 8085
logging:
  level:
    level: info
  file:
    name: logs/mall-coupon.log

