server:
  port: ${port:8080}
spring:
  application:
    name: mall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8849
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
  compression:
    request:
      enabled: true
      mime-types:  text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      useGzipDecoder: true


logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    com.mf: debug