spring:
  application:
    name: mall-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_user?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
server:
  port: 8089
logging:
  level:
    level: info
  file:
    name: logs/mall-product.log
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.mall.user.model
