spring:
  application:
    name: mall-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_products?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
cacheable:
  expirekey: "{'mall:product::1': '10'}"

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.mall.product.model
server:
  port: 8086
logging:
  level:
    level: info
  file:
    name: logs/mall-product.log
mycacheable:
  rate-limit:
    map:  {getProduct: 10}
