spring:
  application:
    name: mall-order
  #???????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_order?useInformationSchema=false&charset=utf8mb4&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mf.mall.order.model
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
server:
  port: 8084
logging:
  level:
    level: info
  file:
    name: logs/mall-order.log
mall-coupon:
  ribbon:
    listOfServers: http://localhost:8085

